var fruits;
fruits = ['mango', 'banana', 'orange', 'apple'];
console.log("Fruits array :" + fruits);
var animals;
animals = ['cat', 'dog', 'rabbit'];
console.log("Animal Array : " + animals);
var persons;
persons = ['Nilesh', 20, 'sachin', 10, 'Dhoni', 7];
console.log("Person Array : " + persons);
var arr;
arr = ['Nilesh', 10, 12.55, true];
console.log("Array of any type :  " + arr);
